### ISSUE TITLE
Baixar dados do repositório /pythonbrasil/dados

### ISSUE THREAD

**Issue by rougeth** [pybropendata/pythonbrasil-opendata#33]
Abrindo uma issue pra discutir uma ideia, seria interessante, ao invés de duplicar os dados, buscá-los diretamente no repositório [/pythonbrasil/dados](https://github.com/pythonbrasil/dados). Uma forma fácil de fazer, seria compilar os .csv disponíveis por lá, e criar uma página no github.io, dessa forma, os arquivos ficariam expostos e poderiam ser compilados aqui.

O que acham?

**Comment by gabubellon** [comment]
@rougeth  eu já busco os dados diretamente de [lá](https://github.com/pybropendata/pythonbrasil-opendata/blob/7516c3eee968dcf1c60cc45ab79b4148cd83f4a7/src/util.py#L16) e salvo localmente mas ele faz o download local a toda nova instancia. Por enquanto isso não causa muito estrago, mas poode ser um ponto de leak de memória em algum momento muito futuro.

**Comment by rougeth** [comment]
Boa! Vacilei em não olhar direito como tava sendo feito. Fechando a issue, mas se achar que uma API servindo do lado de lá ajuda em alguma coisa, vamos trocar uma ideia no futuro.
